#Tmux Appearance 

#      General
#-----------------------
set -g status-position bottom
set -g status-interval 5

#-----------------------




#       Color
#-----------------------
 #Base
set -g status-style "fg=white,bg=default"

#-----------------------





#        Left
#-----------------------
set -g status-left-length 100
set -g status-left "| #{user} | #(~/projects/nixos-config/home/tmux/scripts/path.sh '#{pane_current_path}') | "

#-----------------------


#       Center
#-----------------------
 #24-hour clock: hour:minute day-month-year
set -g status-right-length 100
set -g status-right "%H:%M %d-%m-%Y"

#-----------------------


#       Right
#-----------------------

#-----------------------


#       Windows
#-----------------------
 #Inactive Windows
set -g window-status-format " #I:#W "
 
 #Active Windows
set -g window-status-current-format "#[bold][ #I:#W ]#[nobold]"

#-----------------------





#       Panes
#-----------------------
set -g pane-border-style "fg=white"
set -g pane-active-border-style "fg=white"

#----------------------




#      Messages
#----------------------
set -g message-style "fg=white,bg=default"
